// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually, unless you know your concept requires a custom instantiation procedure.

import { SyncConcept } from "@engine";

export const Engine = new SyncConcept();

import { testDb } from "@utils/database.ts";

import CollectingConcept from "./Collecting/CollectingConcept.ts";
import ProfileConcept from "./Profile/ProfileConcept.ts";
import RecipeConcept from "./Recipe/RecipeConcept.ts";
import RequestingConcept from "./Requesting/RequestingConcept.ts";
import UserConcept from "./User/UserConcept.ts";
import UserAuthenticationConcept from "./UserAuthentication/UserAuthenticationConcept.ts";

export type { default as CollectingConcept } from "./Collecting/CollectingConcept.ts";
export type { default as ProfileConcept } from "./Profile/ProfileConcept.ts";
export type { default as RecipeConcept } from "./Recipe/RecipeConcept.ts";
export type { default as RequestingConcept } from "./Requesting/RequestingConcept.ts";
export type { default as UserConcept } from "./User/UserConcept.ts";
export type { default as UserAuthenticationConcept } from "./UserAuthentication/UserAuthenticationConcept.ts";

// Initialize the database connection
export const [db, client] = await testDb();

export const Collecting = Engine.instrumentConcept(new CollectingConcept(db));
export const Profile = Engine.instrumentConcept(new ProfileConcept(db));
export const Recipe = Engine.instrumentConcept(new RecipeConcept(db));
export const Requesting = Engine.instrumentConcept(new RequestingConcept(db));
export const User = Engine.instrumentConcept(new UserConcept(db));
export const UserAuthentication = Engine.instrumentConcept(new UserAuthenticationConcept(db));
